# Generated by Django 5.2 on 2025-04-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='provider',
            field=models.CharField(default='email', max_length=50),
        ),
    ]
