import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import { ThemeProvider } from "next-themes";
import Footer from "@/components/footer";
import ReactQueryProvider from "@/providers/reactQueryProvider";
import ScrollToTop from "@/components/scrollToTop";

export const metadata: Metadata = {
  title: "Next Pizza | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className="overflow-x-hidden">
        <main className="max-w-7xl antialiased mx-auto flex flex-col justify-center items-center overflow-x-hidden">
          <ReactQueryProvider>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
              <Header />
              {children}
              <Footer />
            </ThemeProvider>
          </ReactQueryProvider>
          <ScrollToTop />
        </main>
      </body>
    </html>
  );
}
