# Generated by Django 5.2 on 2025-04-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_total_order_final_total_order_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('card', 'Card'), ('cash', 'Cash')], default='card', max_length=10),
        ),
    ]
