# Generated by Django 5.2 on 2025-04-19 13:51

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_card_mask_order_card_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_token_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='success_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='order',
            name='token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 20, 13, 51, 6, 75802, tzinfo=datetime.timezone.utc)),
        ),
    ]
