# Generated by Django 5.2 on 2025-04-22 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_payment_date_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 23, 0, 8, 12, 650845, tzinfo=datetime.timezone.utc)),
        ),
    ]
