# Generated by Django 5.2 on 2025-04-23 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_token_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 24, 22, 54, 57, 287600, tzinfo=datetime.timezone.utc)),
        ),
    ]
