# Generated by Django 5.2 on 2025-04-26 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_token_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 27, 19, 21, 44, 267995, tzinfo=datetime.timezone.utc)),
        ),
    ]
