# Generated by Django 5.2 on 2025-04-26 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_token_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 27, 20, 25, 49, 511976, tzinfo=datetime.timezone.utc)),
        ),
    ]
