# Generated by Django 5.2 on 2025-04-26 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_token_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 27, 21, 12, 33, 436918, tzinfo=datetime.timezone.utc)),
        ),
    ]
