# Generated by Django 5.2 on 2025-04-28 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_token_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session_key',
            field=models.CharField(blank=True, help_text='Ключ сессии пользователя, чтобы потом очищать корзину', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 29, 12, 34, 43, 97622, tzinfo=datetime.timezone.utc)),
        ),
    ]
