# Generated by Django 5.2 on 2025-04-29 03:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_session_key_alter_order_token_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 30, 3, 1, 59, 863401, tzinfo=datetime.timezone.utc)),
        ),
    ]
