# Generated by Django 5.2 on 2025-04-06 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('img_url', models.URLField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('img_url', models.URLField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('product_type', models.CharField(choices=[('Pizzas', 'Pizzas'), ('Snacks', 'Snacks'), ('Beverages', 'Beverages'), ('Cocktails', 'Cocktails'), ('Cofe', 'Cofe'), ('Desserts', 'Desserts'), ('Sauces', 'Sauces')], max_length=50)),
                ('img_url', models.URLField()),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=4)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('extra_info', models.CharField(blank=True, max_length=50)),
                ('extra_options', models.ManyToManyField(blank=True, related_name='products', to='products.extraoption')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveSmallIntegerField(blank=True, help_text='Размер в см (если применимо)', null=True)),
                ('grams', models.PositiveIntegerField(blank=True, help_text='Вес в граммах', null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
        ),
    ]
