# Generated by Django 5.2 on 2025-04-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productvariant_grams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Pizzas', 'Pizzas'), ('Snacks', 'Snacks'), ('Beverages', 'Beverages'), ('Cocktails', 'Cocktails'), ('Coffe', 'Coffe'), ('Desserts', 'Desserts'), ('Sauces', 'Sauces')], max_length=50),
        ),
    ]
