# Generated by Django 5.2 on 2025-04-29 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Pizzas', 'Pizzas'), ('Snacks', 'Snacks'), ('Beverages', 'Beverages'), ('Cocktails', 'Cocktails'), ('Coffe', 'Coffe'), ('Desserts', 'Desserts'), ('Sauces', 'Sauces')], db_index=True, max_length=50),
        ),
    ]
